<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Incidentary.Sdk.Integrations.EntityFrameworkCore</PackageId>
    <Description>Entity Framework Core interceptor for Incidentary SDK. Automatic db_query event recording.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Incidentary.Sdk/Incidentary.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

</Project>
