<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Incidentary.Sdk.Integrations.MassTransit</PackageId>
    <Description>MassTransit integration for Incidentary SDK. Automatic queue_publish/queue_consume event recording.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Incidentary.Sdk/Incidentary.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.Abstractions" />
  </ItemGroup>

</Project>
